"""initial schema

Revision ID: eac2708381ee
Revises: 
Create Date: 2026-05-20 10:06:07.501517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eac2708381ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tijdstip', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor', sa.UUID(), nullable=True),
    sa.Column('entiteit', sa.String(length=100), nullable=False),
    sa.Column('entiteit_id', sa.UUID(), nullable=True),
    sa.Column('actie', sa.String(length=50), nullable=False),
    sa.Column('oude_waarde', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nieuwe_waarde', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cao_kalender',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('is_feestdag', sa.Boolean(), nullable=False),
    sa.Column('omschrijving', sa.String(length=200), nullable=True),
    sa.Column('aangemaakt_op', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('gewijzigd_op', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('datum')
    )
    op.create_table('loonschaal',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('omschrijving', sa.String(length=200), nullable=True),
    sa.Column('uurtarief', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('geldig_van', sa.Date(), nullable=False),
    sa.Column('geldig_tot', sa.Date(), nullable=True),
    sa.Column('aangemaakt_op', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('gewijzigd_op', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planning_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bron_bestand', sa.String(length=500), nullable=True),
    sa.Column('vorige_run_id', sa.UUID(), nullable=True),
    sa.Column('geimporteerd_door', sa.UUID(), nullable=True),
    sa.Column('aangemaakt_op', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('gewijzigd_op', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vorige_run_id'], ['planning_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toeslag_regel',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('omschrijving', sa.String(length=200), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('weekdagen', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('minuut_van', sa.Integer(), nullable=False),
    sa.Column('minuut_tot', sa.Integer(), nullable=False),
    sa.Column('alleen_feestdag', sa.Boolean(), nullable=False),
    sa.Column('voorwaarde', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prioriteit', sa.Integer(), nullable=False),
    sa.Column('geldig_van', sa.Date(), nullable=False),
    sa.Column('geldig_tot', sa.Date(), nullable=True),
    sa.Column('aangemaakt_op', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('gewijzigd_op', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uzb',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('naam', sa.String(length=200), nullable=False),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('factuur_prefix', sa.String(length=50), nullable=True),
    sa.Column('afronding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actief', sa.Boolean(), nullable=False),
    sa.Column('aangemaakt_op', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('gewijzigd_op', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('naam')
    )
    op.create_table('factuur',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uzb_id', sa.UUID(), nullable=False),
    sa.Column('factuurnummer', sa.String(length=100), nullable=True),
    sa.Column('bron_bestand', sa.String(length=500), nullable=True),
    sa.Column('totaal_bedrag', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('aangemaakt_op', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('gewijzigd_op', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uzb_id'], ['uzb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registratie_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uzb_id', sa.UUID(), nullable=False),
    sa.Column('bron_bestand', sa.String(length=500), nullable=True),
    sa.Column('vorige_run_id', sa.UUID(), nullable=True),
    sa.Column('geimporteerd_door', sa.UUID(), nullable=True),
    sa.Column('aangemaakt_op', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('gewijzigd_op', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uzb_id'], ['uzb.id'], ),
    sa.ForeignKeyConstraint(['vorige_run_id'], ['registratie_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uzk',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uzb_id', sa.UUID(), nullable=False),
    sa.Column('externe_code', sa.String(length=100), nullable=True),
    sa.Column('naam', sa.String(length=200), nullable=False),
    sa.Column('loonschaal_code', sa.String(length=50), nullable=True),
    sa.Column('actief', sa.Boolean(), nullable=False),
    sa.Column('aangemaakt_op', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('gewijzigd_op', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uzb_id'], ['uzb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verzending',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uzb_id', sa.UUID(), nullable=False),
    sa.Column('iso_jaar', sa.Integer(), nullable=False),
    sa.Column('iso_week', sa.Integer(), nullable=False),
    sa.Column('bestand_pad', sa.String(length=500), nullable=True),
    sa.Column('verzonden_op', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verzonden_door', sa.UUID(), nullable=True),
    sa.Column('aangemaakt_op', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('gewijzigd_op', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uzb_id'], ['uzb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_periode',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uzk_id', sa.UUID(), nullable=False),
    sa.Column('iso_jaar', sa.Integer(), nullable=False),
    sa.Column('iso_week', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('afwijkingen', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gevalideerd_door', sa.UUID(), nullable=True),
    sa.Column('gevalideerd_op', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aangemaakt_op', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('gewijzigd_op', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uzk_id'], ['uzk.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planning_regel',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('uzk_id', sa.UUID(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('begin', sa.Time(), nullable=False),
    sa.Column('eind', sa.Time(), nullable=False),
    sa.Column('geplande_minuten', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['planning_run.id'], ),
    sa.ForeignKeyConstraint(['uzk_id'], ['uzk.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registratie_regel',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('uzk_id', sa.UUID(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('begin', sa.Time(), nullable=False),
    sa.Column('eind', sa.Time(), nullable=False),
    sa.Column('gewerkte_minuten', sa.Integer(), nullable=False),
    sa.Column('pauze_minuten', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['registratie_run.id'], ),
    sa.ForeignKeyConstraint(['uzk_id'], ['uzk.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekrooster',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uzk_id', sa.UUID(), nullable=False),
    sa.Column('iso_jaar', sa.Integer(), nullable=False),
    sa.Column('iso_week', sa.Integer(), nullable=False),
    sa.Column('norm_minuten', sa.Integer(), nullable=False),
    sa.Column('week_50u_uitzondering', sa.Boolean(), nullable=False),
    sa.Column('aangemaakt_op', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('gewijzigd_op', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uzk_id'], ['uzk.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('berekende_uren',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('netto_minuten', sa.Integer(), nullable=False),
    sa.Column('minuten_per_percentage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trace', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('aangemaakt_op', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('gewijzigd_op', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match_periode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factuur_regel',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('factuur_id', sa.UUID(), nullable=False),
    sa.Column('omschrijving', sa.String(length=500), nullable=True),
    sa.Column('uzk_naam_ruw', sa.String(length=200), nullable=True),
    sa.Column('match_id', sa.UUID(), nullable=True),
    sa.Column('match_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('uren', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('bedrag', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['factuur_id'], ['factuur.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match_periode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('factuur_regel')
    op.drop_table('berekende_uren')
    op.drop_table('weekrooster')
    op.drop_table('registratie_regel')
    op.drop_table('planning_regel')
    op.drop_table('match_periode')
    op.drop_table('verzending')
    op.drop_table('uzk')
    op.drop_table('registratie_run')
    op.drop_table('factuur')
    op.drop_table('uzb')
    op.drop_table('toeslag_regel')
    op.drop_table('planning_run')
    op.drop_table('loonschaal')
    op.drop_table('cao_kalender')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
